sudo: no

language: python

python:
  - 3.3
  - 3.4
  - 3.5


cache:
  directories:
  - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - python setup.py develop


script:
  - flake8 pyaspeller
  - py.test --cov=pyaspeller tests
  - coverage run --source=pyaspeller setup.py test
  - python setup.py check -rm


after_success:
    coveralls