sudo: no

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5


cache:
  directories:
  - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


install:
  - pip install --upgrade pip wheel setuptools
  - pip install -r requirements-dev.txt
  - python setup.py develop


script:
  - flake8 . --filename=__init__.py --ignore=F401
  - flake8 . --exclude=__init__.py
  - flake8 pyaspeller
  - py.test --cov=pyaspeller tests
  - python setup.py check -rm


after_success:
    coveralls